### ISSUE TITLE
LiveStreamingServerNet.StandaloneDemo release mode issue

### ISSUE THREAD

**Issue by ntuchenxy** [josephnhtam/live-streaming-server-net#68]
I am running StandaloneDemo and it works fine in debug mode, but when I publish it to release mode, I cannot access the AdminPanelUI (http://127.0.0.1:5000/ui) webpage and it displays the following error message:

`info: LiveStreamingServerNet.Networking.Server.Internal.Server[306231387]
      Server is started | IPEndPoint: 0.0.0.0:1935
info: LiveStreamingServerNet.Networking.Server.Internal.Server[306231387]
      Server is started
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: E:\MyProgram\NET\2024\WireWound\WireWound.StreamingServer\bin\Release\net8.0\publish\win-x64
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://127.0.0.1:5000/ui/streams - - -
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN76RKI4M5LF", Request id "0HN76RKI4M5LF:00000001": An unhandled exception was thrown by the application.
      System.ArgumentNullException: Value cannot be null. (Parameter 'options.FileProvider')
         at System.ArgumentNullException.Throw(String paramName)
         at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
         at LiveStreamingServerNet.AdminPanelUI.AdminPanelUIFileContext..ctor(AdminPanelUIOptions options)
         at LiveStreamingServerNet.AdminPanelUI.AdminPanelUIMiddleware.TryServeAdminPanelUI(HttpContext context)
         at LiveStreamingServerNet.AdminPanelUI.AdminPanelUIMiddleware.InvokeAsync(HttpContext context)
         at LiveStreamingServerNet.Flv.Middlewares.HttpFlvMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://127.0.0.1:5000/ui/streams - 500 0 - 55.3265ms`

**Comment by josephnhtam** [comment]
Hi @ntuchenxy 

Can you share your command to publish?
I have tried `dotnet publish -o ./publish`, which works for me.

**Comment by josephnhtam** [comment]
Hi @ntuchenxy 

Can you share your command to publish?
Anyway, it is more recommended to install the nuget package instead.

**Comment by ntuchenxy** [comment]
Thanks for your response. I think I have found the cause of the problem.
I directly use VS2022 for project publishing, and I set PublishSingleFile=true, that is why admin-panel-ui can not find some files.
