### ISSUE TITLE
RTMP input failure using IRL Pro

### ISSUE THREAD

**Issue by codingaddicted** [josephnhtam/live-streaming-server-net#74]
I open this issue to ask you a support for investigating an injestion issue from a specific client. I know that probably it isn't an actual issue on your library, but I can't figure out what is happing on streaming server side.

To reduce variables for my test I used one of your sample projects (instead of my application which embeds the library), the HLS adaptive transcoding in particular, with this configuration:

```cs
return LiveStreamingServerBuilder.Create()
            .ConfigureRtmpServer(options => options
                .Configure(options => options.EnableGopCaching = false)
                .AddAudioCodecFilter(builder => builder.Include(LiveStreamingServerNet.Rtmp.AudioCodec.AAC))
            .AddStreamProcessor(options =>
            {
                options.AddStreamProcessorEventHandler(svc =>
                        new StreamProcessorEventListener(outputDir, svc.GetRequiredService<ILogger<StreamProcessorEventListener>>()));
            })
            .AddAdaptiveHlsTranscoder(options =>
            {
                options.FFmpegPath = ExecutableFinder.FindExecutable(Path.Combine(Directory.GetCurrentDirectory(), "tools"), "ffmpeg")?.FullName!;
                options.FFprobePath = ExecutableFinder.FindExecutable(Path.Combine(Directory.GetCurrentDirectory(), "tools"), "ffprobe")?.FullName!;
                
                options.DownsamplingFilters = [
                    new DownsamplingFilter(
                        Name: "480p",
                        Height: 480,
                        MaxVideoBitrate: "1500k",
                        MaxAudioBitrate: "128k"
                    ),

                    new DownsamplingFilter(
                        Name: "720p",
                        Height: 720,
                        MaxVideoBitrate: "3000k",
                        MaxAudioBitrate: "256k"
                    ),

                    new DownsamplingFilter(
                        Name: "1080p",
                        Height: 1080,
                        MaxVideoBitrate: "6000k",
                        MaxAudioBitrate: "256k"
                    ),

                    new DownsamplingFilter(
                        Name: "4k",
                        Height: 2160,
                        MaxVideoBitrate: "10000k",
                        MaxAudioBitrate: "256k"
                    )
                ];

                // Hardware acceleration 
                // options.VideoDecodingArguments = "-hwaccel auto -c:v h264_cuvid";
                // options.VideoEncodingArguments = "-c:v h264_nvenc -g 30";

                // bypass audio encoding
                options.AudioEncodingArguments = "-c:a copy";

                options.OutputPathResolver = new HlsOutputPathResolver(outputDir);
            })
```

For my test I used three different clients:
- Larix broadcaster
- OBS
- IRL Pro

all configured the same with H.264 video encoding, 1920 resolution and 30fps.

When I start the streaming client both from Larix and OBS everything works fine, the streaming processor starts and the output ts/m3u8 files are generated.
On the contrary, using **IRL Pro** (which is almost identical from Larix) I receive an error on ffprobe:

```bash
fail: LiveStreamingServerNet.StreamProcessor.Internal.Hls.AdaptiveTranscoding.AdaptiveHlsTranscoder[845055920]
      An error occurred while obtaining stream information | InputPath: rtmp://localhost:1935/live/test?code=49416770426267444139517334356239345670746F364F7739745A6A336B726D6833787943326C474F31313632674B53376E486A6E644A4E43356B7430744764
      System.OperationCanceledException: The operation was canceled.
         at System.Threading.CancellationToken.ThrowOperationCanceledException()
         at System.Threading.CancellationToken.ThrowIfCancellationRequested()
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
         at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken)
         at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
         at System.IO.StreamReader.ReadToEndAsyncInternal(CancellationToken cancellationToken)
         at LiveStreamingServerNet.StreamProcessor.Internal.FFprobe.FFprobeProcess.ExecuteAsync(String inputPath, CancellationToken cancellation)
         at LiveStreamingServerNet.StreamProcessor.Internal.FFprobe.FFprobeProcess.ExecuteAsync(String inputPath, CancellationToken cancellation)
         at LiveStreamingServerNet.StreamProcessor.Internal.Hls.AdaptiveTranscoding.AdaptiveHlsTranscoder.ObtainStreamInformation(String inputPath, CancellationToken cancellation)
```

I get a similar situation if I modify the server configuration to only use HLS transmuxing instead of transcoding, with IRL Pro not working and server simply dropping the connection (without any error in this case).

I hope you can address me to find a solution for this.

Thank you

**Comment by josephnhtam** [comment]
Thank you for reporting this, which seems to be a bug where ffprobe/ffmpeg cannot connect to the local server when it is not bound to 127.0.0.1

**Comment by codingaddicted** [comment]
I refreshed the sample project and I can confirm that now it works even with IRL Pro. I haven't investigate on the cause further yet, but the previous version of the sample was on v0.12.0, so between that versione and the latest one something changed the some behavior. 
Thank you for your time, I really appreciate that.
