### ISSUE TITLE
StreamProcessorException: Error running FFmpeg process - FFmpeg process exited with code -1073741515

### ISSUE THREAD

**Issue by studentnumber9** [josephnhtam/live-streaming-server-net#76]
We are using ffmpeg to make a copy of the stream while it is being viewed.  Everything works in IIS on my dev machine, but in production ffmpeg is exiting with code -1073741515.  The obvious issue to check was permissions, but the app identity has read/execute permissions on ffmpeg.exe and read/write permissions on the UNC share it is trying to write the file to.  I also changed the output path to a subfolder of the web app to eliminate UNC issues.

Unfortunately I didn't get a hit on that exit code, so wanted to check with you.

I haven't yet tried launching FFmpeg myself instead of through the StreamProcessor. Or its verbose mode.  Here is the configuration we are using and the error message we get.

```
                        options.AddStreamProcessor().AddFFmpeg(options =>
                        {
                            options.Name = "mp4-archive";
                            var ffmpegPath = @"FFmpeg";
                            options.FFmpegPath = ExecutableFinder.FindExecutable(ffmpegPath, "ffmpeg").FullName!;
                            options.FFmpegArguments = "-i {inputPath} -c:v copy -c:a copy -preset ultrafast -f mp4 {outputPath}";
                            options.OutputPathResolver = new StreamCopyOutputPathResolver(streamingSettings, cacheService);
                        });
```

2024-12-05 01:35:19.8250|INFO|LiveStreamingServerNet.Networking.Server.Internal.Logging.LoggerExtensions.ClientConnected||Connected (ClientId=5)
2024-12-05 01:35:19.8558|INFO|....RtmpStreamEventMonitor.OnRtmpStreamPublishedAsync||Stream published - clientId=5, streamPath=/api/media/stream/transient_20241205013519627_2640731d09fd4f45a4f2f17d527b784a_Tc7r4ZPt3w9LGi5y2H6F
2024-12-05 01:35:19.8558|INFO|LiveStreamingServerNet.Rtmp.Server.Internal.Logging.LoggerExtensions.PublishingStarted||Start publishing successfully (ClientId=5, StreamPath=/api/media/stream/transient_20241205013519627_2640731d09fd4f45a4f2f17d527b784a_Tc7r4ZPt3w9LGi5y2H6F, Type=live)
2024-12-05 01:35:19.8558|INFO|LiveStreamingServerNet.StreamProcessor.Internal.Logging.LoggerExtensions.StartingFFmpegProcess||Starting FFmpeg process (Arguments=-i rtmp://localhost:1935/api/media/stream/transient_20241205013519627_2640731d09fd4f45a4f2f17d527b784a_Tc7r4ZPt3w9LGi5y2H6F?code=6C4373496F385661703433585476646D504C5A694C47614F67316C3774444642666A754D3462557441456B75774535367A6E56336F71687171645233756C394C -c:v copy -c:a copy -preset ultrafast -f mp4 \\1.2.3.4\Vid01\1\2024\12\869247060028542_20241205013519763_2_2_Co32ZyPt8j6TFq59Sgr7.mp4)
2024-12-05 01:35:19.8719|INFO|LiveStreamingServerNet.StreamProcessor.Internal.Logging.LoggerExtensions.StreamProcessorStarted||Stream processor started (StreamProcessor=mp4-archive, Identifier=c40bb39f-419d-4e75-ae4a-9e7e991fbe3e, InputPath=rtmp://localhost:1935/api/media/stream/transient_20241205013519627_2640731d09fd4f45a4f2f17d527b784a_Tc7r4ZPt3w9LGi5y2H6F?code=6C4373496F385661703433585476646D504C5A694C47614F67316C3774444642666A754D3462557441456B75774535367A6E56336F71687171645233756C394C, OutputPath=\\1.2.3.4\Vid01\1\2024\12\869247060028542_20241205013519763_2_2_Co32ZyPt8j6TFq59Sgr7.mp4, StreamPath=/api/media/stream/transient_20241205013519627_2640731d09fd4f45a4f2f17d527b784a_Tc7r4ZPt3w9LGi5y2H6F)
2024-12-05 01:35:19.9398|INFO|LiveStreamingServerNet.StreamProcessor.Internal.Logging.LoggerExtensions.StreamProcessorStopped||Stream processor stopped (StreamProcessor=mp4-archive, Identifier=c40bb39f-419d-4e75-ae4a-9e7e991fbe3e, InputPath=rtmp://localhost:1935/api/media/stream/transient_20241205013519627_2640731d09fd4f45a4f2f17d527b784a_Tc7r4ZPt3w9LGi5y2H6F?code=6C4373496F385661703433585476646D504C5A694C47614F67316C3774444642666A754D3462557441456B75774535367A6E56336F71687171645233756C394C, OutputPath=\\1.2.3.4\Vid01\1\2024\12\869247060028542_20241205013519763_2_2_Co32ZyPt8j6TFq59Sgr7.mp4, StreamPath=/api/media/stream/transient_20241205013519627_2640731d09fd4f45a4f2f17d527b784a_Tc7r4ZPt3w9LGi5y2H6F)
2024-12-05 01:35:19.9398|ERROR|LiveStreamingServerNet.StreamProcessor.Internal.Logging.LoggerExtensions.StreamProcessorError|LiveStreamingServerNet.StreamProcessor.Exceptions.StreamProcessorException: **Error running FFmpeg process**
 ---> LiveStreamingServerNet.StreamProcessor.Exceptions.StreamProcessorException: **FFmpeg process exited with code -1073741515**
   at LiveStreamingServerNet.StreamProcessor.Internal.FFmpeg.FFmpegProcess.RunProcessAsync(String inputPath, String outputPath, OnStreamProcessorStarted onStarted, OnStreamProcessorEnded onEnded, CancellationToken cancellation)
   --- End of inner exception stack trace ---
   at LiveStreamingServerNet.StreamProcessor.Internal.FFmpeg.FFmpegProcess.RunProcessAsync(String inputPath, String outputPath, OnStreamProcessorStarted onStarted, OnStreamProcessorEnded onEnded, CancellationToken cancellation)
   at LiveStreamingServerNet.StreamProcessor.Internal.FFmpeg.FFmpegProcess.RunProcessAsync(String inputPath, String outputPath, OnStreamProcessorStarted onStarted, OnStreamProcessorEnded onEnded, CancellationToken cancellation)
   at LiveStreamingServerNet.StreamProcessor.Internal.FFmpeg.FFmpegProcess.RunAsync(String inputPath, String streamPath, IReadOnlyDictionary`2 streamArguments, OnStreamProcessorStarted onStarted, OnStreamProcessorEnded onEnded, CancellationToken cancellation)
   at LiveStreamingServerNet.StreamProcessor.Internal.Services.StreamProcessorManager.RunStreamProcessor(IStreamProcessor streamProcessor, ISessionHandle client, String streamPath, IReadOnlyDictionary`2 streamArguments, CancellationTokenSource cts)|Stream processor error (InputPath=rtmp://localhost:1935/api/media/stream/transient_20241205013519627_2640731d09fd4f45a4f2f17d527b784a_Tc7r4ZPt3w9LGi5y2H6F?code=6C4373496F385661703433585476646D504C5A694C47614F67316C3774444642666A754D3462557441456B75774535367A6E56336F71687171645233756C394C, StreamPath=/api/media/stream/transient_20241205013519627_2640731d09fd4f45a4f2f17d527b784a_Tc7r4ZPt3w9LGi5y2H6F)
2024-12-05 01:35:19.9398|INFO|....RtmpStreamEventMonitor.OnRtmpStreamUnpublishedAsync||Stream Unpublished - clientId=5, streamPath=/api/media/stream/transient_20241205013519627_2640731d09fd4f45a4f2f17d527b784a_Tc7r4ZPt3w9LGi5y2H6F
2024-12-05 01:35:19.9398|INFO|LiveStreamingServerNet.Networking.Server.Internal.Logging.LoggerExtensions.ClientDisconnected||Disconnected (ClientId=5)

**Comment by josephnhtam** [comment]
Hi @studentnumber9 

-1073741515 (0xC0000135) implies dll not found. 
You may need to verify if ffmpeg can run separately first .

**Comment by studentnumber9** [comment]
Thank you for that lead, I innocently thought all one needs is the big 144MB ffmpeg.exe that would include everything, but let me investigate.

**Comment by studentnumber9** [comment]
The Admin found this article [https://superuser.com/questions/1742768/ffmpeg-on-windows-server-core-2022], which has the following instructions, based on which he copied the two dlls to system32.  FFmpeg process now works.

C:\windows\system32\AVICAP32.DLL and C:\windows\system32\MSVFW32.DLL can be copied from Windows Server 2022 LTSC (Desktop Edition) or Windows 10.
Copying those to the system32 folder, ffmpeg.exe should work again.
